logging:
    level:
        org:
            hibernate: ERROR
            springframework:
                web: ERROR

server:
  port: 8081
  servlet:
    context-path: /addr
    
    
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_addr?currentSchema=addr
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12345
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: addr
  config:
    import: "optional:configserver:http://localhost:8071/"  
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"  

    
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json 
  api-docs:
    path: /swagger-ui-custom.html
    
service:
  title: ${spring.application.name} microservice REST API Documentation(${spring.profiles.active})
  version: v-2
  description: GLOBAL CRM microservice REST API Documentation

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "address"
    description: "Global Address Application"
    version: "1.0.0"
