logging:
    level:
        org:
            hibernate: ERROR
            springframework:
                web: ERROR


server:
  port: 8082
  servlet:
    context-path: /mdm
    
    
spring:
  datasource:
    url: jdbc:postgresql://3.111.113.117:5432/crm_mdm?currentSchema=mdm
    driverClassName: org.postgresql.Driver
    username: app_user
    password: 12345
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: mdm
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"  

    
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json 
  api-docs:
    path: /swagger-ui-custom.html
    
service:
  title: ${spring.application.name} microservice REST API Documentation(${spring.profiles.active})
  version: v1
  description: GLOBAL CRM microservice REST API Documentation

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "MDM"
    description: "Global MDM Application"
    version: "1.0.0"      
